version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/dscantool/dscan/static
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
volumes:
  postgres_data:
  static_volume:

